language: rust
cache: cargo

before_install:
  - sudo apt-get install -y libvips
  - cargo build --verbose

rust:
  - stable
  - beta
  
  
matrix:
  install:
    - apt install libvips
    - cargo build --verbose
  allow_failures:
    - rust: beta
  fast_finish: true
script:
- rustup component add rustfmt-preview
- cargo fmt --all -- --check
- cargo test --verbose
- cargo doc
