sudo: false

language: rust

env:
  global:
    - VIPS_VERSION=8.6.5
    - LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
    - PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH
    - PATH=$HOME/.cargo/bin:$HOME/vips/bin:$PATH

addons:
  apt:
    packages:
      - ca-certificates
      - wget
      - build-essential
      - glib2.0-dev
      - libxml2-dev
      - libjpeg-turbo8-dev
      - libexif-dev
      - libtiff5-dev
      - libgsf-1-dev
      - libpng-dev
      - libexpat-dev

cache:
  cargo: true
  directories:
    - $HOME/vips

rust:
  - stable
  - beta
  - nightly

stages:
  - lint
  - test

before_script:
  - ./ci/install-vips.sh

script:
  - cargo test --verbose
  - cargo doc

jobs:
  include:
    - stage: lint
      rust: nightly
      script:
        - export PATH="$PATH:~/.cargo/bin"
        - cargo +nightly fmt -- --version || cargo +nightly install rustfmt-nightly --force
        - cargo +nightly fmt --all -- --check

matrix:
  allow_failures:
    - rust: nightly
      stage: test
    - rust: beta
  fast_finish: true
