language: rust
cache: cargo

before_install:
  - sudo apt-get install -y libvips pkg-config

rust:
  - stable
  - beta
  
  
matrix:
  allow_failures:
    - rust: beta
  fast_finish: true
script:
- rustup component add rustfmt-preview
- cargo fmt --all -- --check
- cargo test --verbose
- cargo doc
