sudo: required
language: rust
cache: cargo

env:
  global:
    - VIPS_VERSION=8.6.5

rust:
  - stable
  - beta
  - nightly

stages:
  - lint
  - test

before_script:
  - ./install-vips.sh

script:
  - cargo test --verbose
  - cargo doc

jobs:
  include:
    - stage: lint
      rust: nightly
      script:
        - export PATH="$PATH:~/.cargo/bin"
        - cargo +nightly fmt -- --version || cargo +nightly install rustfmt-nightly --force
        - cargo +nightly fmt --all -- --check

matrix:
  allow_failures:
    - rust: nightly
      stage: test
    - rust: beta
  fast_finish: true
