[package]
name = "optimal-image"
version = "0.1.0"
authors = ["amoretti <andrea.moretti@zalando.de>"]

[dependencies]
dssim = "2.9.9"
image = "0.19.0"
imgref = "1.3.5"
lodepng = "2.1.2"

[[bin]]
name = "optimizer"
path = "src/main.rs"

[lib]
name = "optimizer"
path = "src/optimizer/lib.rs"
